/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Clases.*;
import Frames.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author E - l - l - e - r - y Y Carlos
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    //Arrays
    static public ArrayList<ObraDTeatro> obras = new ArrayList();
    static public ArrayList<SalaTeatro> salas = new ArrayList();

    public Main() {
        initComponents();

        //Salas Predeterminadas//
        salas.add(new SalaTeatro(1, 35));
        salas.add(new SalaTeatro(2, 45));
        salas.add(new SalaTeatro(3, 70));
        salas.add(new SalaTeatro(4, 80));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemRgtObra = new javax.swing.JMenuItem();
        itemAsignarSala = new javax.swing.JMenuItem();
        itemVenderBoleto = new javax.swing.JMenuItem();
        itemDesasignarSala = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemConsultaObra = new javax.swing.JMenuItem();
        ItemConsultaSala = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teatro Amira");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenu1.setText("Obras del teatro");

        itemRgtObra.setText("Registrar nueva obra");
        itemRgtObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRgtObraActionPerformed(evt);
            }
        });
        jMenu1.add(itemRgtObra);

        itemAsignarSala.setText("Asignar Sala");
        itemAsignarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarSalaActionPerformed(evt);
            }
        });
        jMenu1.add(itemAsignarSala);

        itemVenderBoleto.setText("Vender Boleto");
        itemVenderBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVenderBoletoActionPerformed(evt);
            }
        });
        jMenu1.add(itemVenderBoleto);

        itemDesasignarSala.setText("Desasignar Sala");
        itemDesasignarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesasignarSalaActionPerformed(evt);
            }
        });
        jMenu1.add(itemDesasignarSala);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Información del teatro");

        itemConsultaObra.setText("Consultas Obras");
        itemConsultaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaObraActionPerformed(evt);
            }
        });
        jMenu2.add(itemConsultaObra);

        ItemConsultaSala.setText("Consultas Salas");
        ItemConsultaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultaSalaActionPerformed(evt);
            }
        });
        jMenu2.add(ItemConsultaSala);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRgtObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRgtObraActionPerformed
        // TODO add your handling code here:
        Registrar r = new Registrar();
        escritorio.add(r);
        r.show();
    }//GEN-LAST:event_itemRgtObraActionPerformed

    private void itemConsultaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaObraActionPerformed
        // TODO add your handling code here:
        if(obras.isEmpty()){
            JOptionPane.showMessageDialog(null,"No hay obras registradas");
        } else {
            
            ConsultaObras co = new ConsultaObras();
            escritorio.add(co);
            co.show();
            
        }
        
    }//GEN-LAST:event_itemConsultaObraActionPerformed

    private void itemAsignarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarSalaActionPerformed
        // TODO add your handling code here:
        AsignarSala as = new AsignarSala();
        escritorio.add(as);
        as.show();

    }//GEN-LAST:event_itemAsignarSalaActionPerformed

    private void itemDesasignarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesasignarSalaActionPerformed
        // TODO add your handling code here:
        ArrayList<ObraDTeatro> validar = new ArrayList();

        for (int i = 0; i < obras.size(); i++) {
            if (obras.get(i).getSalaAsignada() != null) {
                validar.add(obras.get(i));
            }
        }

        if (validar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay registro de obras con salas asignadas");
        } else {
            DesasignarSala ds = new DesasignarSala();

            escritorio.add(ds);
            ds.show();
        }

    }//GEN-LAST:event_itemDesasignarSalaActionPerformed

    private void itemVenderBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVenderBoletoActionPerformed
        // TODO add your handling code here:
        ArrayList<ObraDTeatro> validar = new ArrayList();

        for (int i = 0; i < obras.size(); i++) {
            if (obras.get(i).getSalaAsignada() != null) {
                validar.add(obras.get(i));
            }
        }

        if (validar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay registro de obras con salas asignadas");
        } else {
            VenderBoleto vb = new VenderBoleto();
            escritorio.add(vb);
            vb.show();
        }
    }//GEN-LAST:event_itemVenderBoletoActionPerformed

    private void ItemConsultaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultaSalaActionPerformed
        // TODO add your handling code here:
        ConsultaSalas cs = new ConsultaSalas();
        escritorio.add(cs);
        cs.show();
    }//GEN-LAST:event_ItemConsultaSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemConsultaSala;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAsignarSala;
    private javax.swing.JMenuItem itemConsultaObra;
    private javax.swing.JMenuItem itemDesasignarSala;
    private javax.swing.JMenuItem itemRgtObra;
    private javax.swing.JMenuItem itemVenderBoleto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
