/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import java.util.ArrayList;
import clases.*;


/**
 *
 * @author HOME
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    //JInternalFrames
    
    
    //Obras
    static public ArrayList<ObraTeatro> obras = new ArrayList();
    
    //Salas
    static public ArrayList<Sala> salas = new ArrayList();
    
    public Principal() {
        initComponents();
        salas.add(new Sala(1,50,null));
        salas.add(new Sala(2,40,null));
        salas.add(new Sala(3,30,null));
        salas.add(new Sala(4,45,null));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sala1 = new javax.swing.JMenuItem();
        sala2 = new javax.swing.JMenuItem();
        sala3 = new javax.swing.JMenuItem();
        sala4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        registrarObra = new javax.swing.JMenuItem();
        consultarObra = new javax.swing.JMenuItem();
        ventaBoleto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Salas");

        sala1.setText("Sala 1");
        sala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala1ActionPerformed(evt);
            }
        });
        jMenu1.add(sala1);

        sala2.setText("Sala 2");
        sala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala2ActionPerformed(evt);
            }
        });
        jMenu1.add(sala2);

        sala3.setText("Sala 3");
        sala3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala3ActionPerformed(evt);
            }
        });
        jMenu1.add(sala3);

        sala4.setText("Sala 4");
        sala4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala4ActionPerformed(evt);
            }
        });
        jMenu1.add(sala4);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Obras");

        registrarObra.setText("Registrar");
        registrarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarObraActionPerformed(evt);
            }
        });
        jMenu4.add(registrarObra);

        consultarObra.setText("Consultar");
        consultarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarObraActionPerformed(evt);
            }
        });
        jMenu4.add(consultarObra);

        ventaBoleto.setText("Vender Boleto");
        ventaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaBoletoActionPerformed(evt);
            }
        });
        jMenu4.add(ventaBoleto);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sala3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala3ActionPerformed
        // TODO add your handling code here:
        Room3 room3 = new Room3();
        room3.setVisible(true);
    }//GEN-LAST:event_sala3ActionPerformed

    private void sala4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala4ActionPerformed
        // TODO add your handling code here:
        Room4 room4 = new Room4();
        room4.setVisible(true);
    }//GEN-LAST:event_sala4ActionPerformed

    private void sala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala1ActionPerformed
        // TODO add your handling code here:
        Room1 room1 = new Room1();
        room1.setVisible(true);
       
    }//GEN-LAST:event_sala1ActionPerformed

    private void sala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala2ActionPerformed
        // TODO add your handling code here:
        Room2 room2 = new Room2();
        room2.setVisible(true);
    }//GEN-LAST:event_sala2ActionPerformed

    private void registrarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarObraActionPerformed
        // TODO add your handling code here:
        RegistrarObra Obra = new RegistrarObra();
        Obra.setVisible(true);   
    }//GEN-LAST:event_registrarObraActionPerformed

    private void consultarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarObraActionPerformed
        // TODO add your handling code here:
        ConsultasObra consultas = new ConsultasObra();
        consultas.setVisible(true);
    }//GEN-LAST:event_consultarObraActionPerformed

    private void ventaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaBoletoActionPerformed
        // TODO add your handling code here:
        VenderBoleto ventas = new VenderBoleto();
        ventas.setVisible(true);
    }//GEN-LAST:event_ventaBoletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultarObra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem registrarObra;
    private javax.swing.JMenuItem sala1;
    private javax.swing.JMenuItem sala2;
    private javax.swing.JMenuItem sala3;
    private javax.swing.JMenuItem sala4;
    private javax.swing.JMenuItem ventaBoleto;
    // End of variables declaration//GEN-END:variables
}
