/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import clases.*;
import Paneles.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    
    //ArrayList de las Obras
    static public ArrayList<Obra> obras = new ArrayList<>();
    //ArrayList de las Salas (Salas Predeterminadas)
    static public ArrayList<Sala> salas = new ArrayList<>();
    
    public PanelPrincipal() {
        initComponents();
        //Añadiendo Salas
        salas.add(new Sala(1,30));
        salas.add(new Sala(2,50));
        salas.add(new Sala(3,75));
        salas.add(new Sala(4,60));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuObras = new javax.swing.JMenu();
        registrarObra = new javax.swing.JMenuItem();
        itemVenderBoleto = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        itemConsultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuObras.setText("Obras de Teatro");

        registrarObra.setText("Registrar");
        registrarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarObraActionPerformed(evt);
            }
        });
        menuObras.add(registrarObra);

        itemVenderBoleto.setText("Vender Boleto");
        itemVenderBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVenderBoletoActionPerformed(evt);
            }
        });
        menuObras.add(itemVenderBoleto);

        jMenuBar1.add(menuObras);

        Consultas.setText("Consultas");
        Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultasActionPerformed(evt);
            }
        });

        itemConsultas.setText("Consultas");
        itemConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultasActionPerformed(evt);
            }
        });
        Consultas.add(itemConsultas);

        jMenuBar1.add(Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemVenderBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVenderBoletoActionPerformed
        // TODO add your handling code here:
        //Si no hay obras no abre el panel
        if(obras.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay obras registradas !!!");
        } else {
            
            venderBoleto objeto = new venderBoleto();
            objeto.setVisible(true);
            
        }
    }//GEN-LAST:event_itemVenderBoletoActionPerformed

    private void registrarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarObraActionPerformed
        
        registrarObra panel = new registrarObra();
        panel.setVisible(true);
        
    }//GEN-LAST:event_registrarObraActionPerformed

    private void ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultasActionPerformed
       
    }//GEN-LAST:event_ConsultasActionPerformed

    private void itemConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultasActionPerformed
        
        Consultas panel = new Consultas();
        
        panel.setVisible(true);
        
    }//GEN-LAST:event_itemConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem itemConsultas;
    private javax.swing.JMenuItem itemVenderBoleto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuObras;
    private javax.swing.JMenuItem registrarObra;
    // End of variables declaration//GEN-END:variables
}
